name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # This will trigger the workflow on pushes to all branches.

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -f app.dockerfile -t myapp:${{ github.sha }} .

      # - name: Scan for vulnerabilities
      #   run: |
      #     docker run --rm \
      #       -v /var/run/docker.sock:/var/run/docker.sock \
      #       aquasec/trivy image --severity HIGH,CRITICAL myapp:${{ github.sha }}

      # - name: Push Docker image
      #   run: docker push myapp:${{ github.sha }}

  performance-test:
    name: Performance Test
    runs-on: ${{needs.build.outputs.RUNNER}}
    needs: build

    steps:
      - name: Run Application Container
        run: |
          docker run -d --name app_container -p 8080:8080 myapp:${{ github.sha }}

      - name: Make a CURL request  
        run: |
          curl -X GET "http://localhost:8080"   

  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Run performance tests
  #       uses: ./.github/actions/performance-test
  #       with:
  #         docker_image: myapp:${{ github.sha }}